<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByIdJoinedCategoryAndType($idType){
        $query = $this->getEntityManager()
            ->createQuery(
                "Select p.id, p.itemName AS name, cc.categoryName AS category ,p.ingredients,p.itemPrice AS price FROM AppBundle:Item p 
                 JOIN p.category cc
                 JOIN cc.type t 
                 WHERE t.id = :type
                 AND t.id = cc.type 
                 AND cc.id = p.category"
            )->setParameter("type", $idType);
        try{
            return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}
