AppBundle\Entity\Cart:
    type: entity
    manyToOne:
      user:
        targetEntity: AppBundle\Entity\User
        joinColumn:
          name: user_id
          referencedColumnName: id
    manyToMany:
      items:
        targetEntity: AppBundle\Entity\Item
        joinTable:
          name: cart_items
          JoinColumns:
            cart_id:
              referencedColumnName: id
          inverseJoinColumns:
            item_id:
              referencedColumnName: id
    table: null
    repositoryClass: AppBundle\Repository\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: decimal
            precision: 10
            scale: 0
        priceWt:
            type: float
        endPurchase:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
