AppBundle\Entity\Drink:
    type: entity
    manyToOne:
          type:
            targetEntity: AppBundle\Entity\Restaurant
            joinColumn:
              name: type_id
              referencedColumnName: id
    table: null
    repositoryClass: AppBundle\Repository\DrinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        degree:
            type: decimal
            precision: 10
            scale: 0
            nullable: true
        liter:
            type: string
            length: 255
            nullable: true
        price:
            type: decimal
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
