AppBundle\Entity\Item:
    type: entity
    manyToOne:
      category:
        targetEntity: AppBundle\Entity\Category
        inversedBy: item
        joinColumn:
          name: category_id
          referencedColumnName: id
    table: null
    repositoryClass: AppBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        itemName:
            type: string
            length: 255
            column: item_name
        itemPrice:
            type: string
            length: 255
            column: item_price
        ingredients:
            type: array
            column: ingredients
    lifecycleCallbacks: {  }
